import { Inter } from 'next/font/google'
import Header from './components/Header/Header'
import './_generic.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Etraveli Group Star Wars',
  description: 'Generated by Me',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Header />{children}</body>
    </html>
  )
}
